# Data Analysis Techniques. Lab 4. Introduction to `pandas`

## 1. `pandas` data structures

The basic data structures in the pandas library are the dataframe, an object of type `DataFrame`, and the series, `Series`, which constitutes a single column of a dataframe. Underlying these structures are NumPy arrays, which we have already encountered in previous classes. Each column in a dataframe is defined by the data type stored in it, including cases where missing values can also be stored (the `Nan` type—not a number).

### 1.1 Pandas `DataFrame` and `series` initialization

In [ ]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np

In pandas, a DataSeries is a structure that, in addition to data in the form of a vector, also contains an index, which can be of any type, provided it is a hashable type in Python. Below are a few examples of how to initialize a DataSeries.

In [3]:
# How to view the docstring for the pandas.Series class without having to search for it online
print(pd.Series.__doc__)

One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, \*, \*\*) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series. If data is a dict, argument order is
    maintained. Unordered sets are not supported.
index : array-like or Index (1d)
    Values must be hashable and have the same length as `data`.
    Non-unique index values are allowed. Will default to
    RangeIndex (0, 1, 2, ..., n) if not provided. If data is dict-like
    and index is None, then the keys in the data are used as the index. If the
    index is not None, the resulting Series is reindexed with the index values.
dtype : str, numpy.dtype, or ExtensionDtype, optional
    Data type for the output Series. If not specified, this will be
    inferred from `data`.
    See the :ref:`user guide <basics.dtypes>` for more usages.
name : Hashable, default None
    The name to give to the Series.
copy : bool, default None
    Whether to copy input data, only relevant for array, Series, and Index
    inputs (for other input, e.g. a list, a new array is created anyway).
    Defaults to True for array input and False for Index/Series.
    Even when False for Index/Series, a shallow copy of the data is made.
    Set to False to avoid copying array input at your own risk (if you
    know the input data won't be modified elsewhere).
    Set to True to force copying Series/Index input up front.

See Also
--------
DataFrame : Two-dimensional, size-mutable, potentially heterogeneous tabular data.
Index : Immutable sequence used for indexing and alignment.

Notes
-----
Please reference the :ref:`User Guide <basics.series>` for more information.

Examples
--------
Constructing Series from a dictionary with an Index specified

>>> d = {"a": 1, "b": 2, "c": 3}
>>> ser = pd.Series(data=d, index=["a", "b", "c"])
>>> ser
a   1
b   2
c   3
dtype: int64

The keys of the dictionary match with the Index values, hence the Index
values have no effect.

>>> d = {"a": 1, "b": 2, "c": 3}
>>> ser = pd.Series(data=d, index=["x", "y", "z"])
>>> ser
x   NaN
y   NaN
z   NaN
dtype: float64

Note that the Index is first built with the keys from the dictionary.
After this the Series is reindexed with the given Index values, hence we
get all NaN as a result.

Constructing Series from a list with `copy=False`.

>>> r = [1, 2]
>>> ser = pd.Series(r, copy=False)
>>> ser.iloc[0] = 999
>>> r
[1, 2]
>>> ser
0    999
1      2
dtype: int64

Due to input data type the Series has a `copy` of
the original data even though `copy=False`, so
the data is unchanged.

Constructing Series from a 1d ndarray with `copy=False`.

>>> r = np.array([1, 2])
>>> ser = pd.Series(r, copy=False)
>>> ser.iloc[0] = 999
>>> r
array([999,   2])
>>> ser
0    999
1      2
dtype: int64

Due to input data type the Series has a `view` on
the original data, so
the data is changed as well.

**Example 1**

In [4]:
# initialization of an empty pandas series
series_1 = pd.Series()
series_1

Series([], dtype: object)

In [5]:
# main descriptive statistics, we can run this function for a DataFrame
series_1.describe()

count       0
unique      0
top       NaN
freq      NaN
dtype: object

**Example 2**

In [8]:
data = np.arange(1,6)
series_2 = pd.Series(data)
series_2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
# now we can see more as we have a numerical series
series_2.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

**Example 3**

In [10]:
# pandas series from a Python dictionary
data = {key: val for key,val in zip('abcd',[1,2,3,4])}
print(f"Dict: {data}")
series_3 = pd.Series(data)
series_3

Dict: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
series_3.index

Index(['a', 'b', 'c', 'd'], dtype='str')

**Example 4**

In [12]:
# we can convert pandas series to a python list
# methods tolist() and to_list()
series_3.tolist()

[1, 2, 3, 4]

In [13]:
series_3.index.tolist()

['a', 'b', 'c', 'd']

**Example 5**

In [14]:
# Looking at the docstring for Series, we can see that arithmetic operations on data series are also possible
# provided that certain rules are followed (the length of the data series vector)
series_3 + series_3

a    2
b    4
c    6
d    8
dtype: int64

In [15]:
series_3 ** 2

a     1
b     4
c     9
d    16
dtype: int64

In [16]:
series_3

a    1
b    2
c    3
d    4
dtype: int64

**Example 6**

In [31]:
# We can also take advantage of certain features of the NumPy library related to returning copies and views of arrays
# Below is an example showing how to create a data series that is a view of a NumPy array
arr = np.arange(1, 6)
print(arr)
series_4 = pd.Series(arr, copy=False)
series_4

[1 2 3 4 5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [35]:
# The `values` attribute returns the series data as a NumPy array
# We compare the addresses of both arrays—if they match, they point to the same memory location
series_4.values.base == arr.base

True

In [36]:
# This allows us to share this memory, along with all its benefits
# and drawbacks (less memory allocated, but no data isolation
# in the event of modifications made through any of the views)

# Modifying the variable naturally updates its value across all views
arr[0] = 99
print(arr)
print(series_4)

[99  2  3  4  5]
0    99
1     2
2     3
3     4
4     5
dtype: int64

**Example 7**

In [ ]:
# You can name a data series, although this is not often done in practice
series_4.name = "age"
series_4

**Example 8**

In [47]:
# We generate a time series using the `date_range(start, number_of_periods, interval)` function
timeseries = pd.date_range('2025-03-20 12:00:00', periods=6, freq='h')
timeseries

DatetimeIndex(['2025-03-20 12:00:00', '2025-03-20 13:00:00',
               '2025-03-20 14:00:00', '2025-03-20 15:00:00',
               '2025-03-20 16:00:00', '2025-03-20 17:00:00'],
              dtype='datetime64[ns]', freq='h')

In [48]:
# The pandas series also has a special index type for time series data
# Here we'll generate such data, but it can also be loaded from files
data = [f'event {n}' for n in range(1, 7)]
timeseries = pd.Series(data, index=timeseries)
timeseries

2025-03-20 12:00:00    event 1
2025-03-20 13:00:00    event 2
2025-03-20 14:00:00    event 3
2025-03-20 15:00:00    event 4
2025-03-20 16:00:00    event 5
2025-03-20 17:00:00    event 6
Freq: h, dtype: object

In [49]:
timeseries.index

DatetimeIndex(['2025-03-20 12:00:00', '2025-03-20 13:00:00',
               '2025-03-20 14:00:00', '2025-03-20 15:00:00',
               '2025-03-20 16:00:00', '2025-03-20 17:00:00'],
              dtype='datetime64[ns]', freq='h')

**DataFrame initialization**

Just as with data series, we can convert other data structures into a data frame, provided certain conditions are met. Let’s start with a list.

**Example 9**

In [18]:
df_1 = pd.DataFrame([f'row {n}' for n in range(1, 6)])
df_1

       0
0  row 1
1  row 2
2  row 3
3  row 4
4  row 5

In [19]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      str
dtypes: str(1)
memory usage: 172.0 bytes

In [20]:
df_1.describe()

            0
count       5
unique      5
top     row 1
freq        1

In [21]:
print(df_1.ndim, df_1.dtypes, df_1.shape, sep='\n')

2
0    str
dtype: object
(5, 1)

In [22]:
df_1.index

RangeIndex(start=0, stop=5, step=1)

In [23]:
# list of columns in DataFrame
df_1.columns

RangeIndex(start=0, stop=1, step=1)

In [24]:
df_1.columns = ['feature 1']
df_1

  feature 1
0     row 1
1     row 2
2     row 3
3     row 4
4     row 5

**Example 10**

In [25]:
# There are many ways to access data within series and charts
# Here, we are referring to a single column, which, as you can see, is the default axis for searching for this value (column label)
df_1['feature 1']

0    row 1
1    row 2
2    row 3
3    row 4
4    row 5
Name: feature 1, dtype: str

In [27]:
# each column is a pandas series
type(df_1['feature 1'])

pandas.Series

**Example 11**

In [28]:
# There is an overloaded DataFrame constructor that, among other things, allows you to convert a nested list
# (in this case, a two-level list) into a DataFrame without any additional transformations
nested_list = [[1,2,3,4] for _ in range(4)]
df_2 = pd.DataFrame(nested_list, columns=list('ABCD'))
df_2

   A  B  C  D
0  1  2  3  4
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4

In [73]:
# `describe` works for all numeric columns
df_2.describe()

         A    B    C    D
count  4.0  4.0  4.0  4.0
mean   1.0  2.0  3.0  4.0
std    0.0  0.0  0.0  0.0
min    1.0  2.0  3.0  4.0
25%    1.0  2.0  3.0  4.0
50%    1.0  2.0  3.0  4.0
75%    1.0  2.0  3.0  4.0
max    1.0  2.0  3.0  4.0

**Example 12**

In [29]:
df_2['D'] = df_2['D'].astype(str)
df_2.describe()

         A    B    C
count  4.0  4.0  4.0
mean   1.0  2.0  3.0
std    0.0  0.0  0.0
min    1.0  2.0  3.0
25%    1.0  2.0  3.0
50%    1.0  2.0  3.0
75%    1.0  2.0  3.0
max    1.0  2.0  3.0

**Example 13**

In [30]:
# Initializing a frame from a dictionary—here's a simple example to illustrate the required dictionary format
# Dictionary keys
data_dict = {'label': 'computer', 'price': 1999.0}
df_3 = pd.DataFrame(data_dict, index=list(range(1)))
df_3

      label   price
0  computer  1999.0

**Example 14**

In [88]:
# This is probably not the result we were expecting
df_4 = pd.DataFrame(data_dict, index=list(range(len(data_dict))))
df_4

      label   price
0  computer  1999.0
1  computer  1999.0

**Przykład 15**

In [91]:
# Now it's better - key: list of values
data_dict = {'label': ['computer', 'monitor', 'mouse'], 'price': [1999.0, 299.0, 30]}
df_5 = pd.DataFrame(data_dict)
df_5

      label   price
0  computer  1999.0
1   monitor   299.0
2     mouse    30.0

**Loading Data into a Frame from Files**

A list of available functions for reading and writing data to and from pandas frames can be found in the documentation at: https://pandas.pydata.org/docs/reference/io.html

Examples using selected options are presented below.

File **iris.data** is in the same folder as this notebook.

In [94]:
# Loading data into a frame from a file
# Displaying the first 5 lines from the file (may not work depending on your operating system configuration)
! head -5 iris.data

sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa

**Example 16**

In [31]:
# We read data into a file using the `read_csv` function with default parameters (delimiter, encoding, error handling, header, and others)
df_6 = pd.read_csv('iris.data')
df_6

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [32]:
df_6.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sepal length in cm  150 non-null    float64
 1   sepal width in cm   150 non-null    float64
 2   petal length in cm  150 non-null    float64
 3   petal width in cm   150 non-null    float64
 4   class               150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

**Example 17**

In [33]:
df_7 = pd.read_table('iris.data', sep=',')
df_7

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

**Example 18**

In [34]:
# If the file does not have a header row, we can specify this option when loading it
# But first, let's save the data to a CSV file using the to_csv function

# file path, separator, whether to save the header, whether to save the index (if it was created
# while loading data into the frame, we usually don’t want to save it), character encoding
df_7.to_csv('iris.csv', sep=';', header=True, index=False, encoding='utf-8')

In [36]:
# migth not work on Windows
!head -5 iris.csv

sepal length in cm;sepal width in cm;petal length in cm;petal width in cm;class
5.1;3.5;1.4;0.2;Iris-setosa
4.9;3.0;1.4;0.2;Iris-setosa
4.7;3.2;1.3;0.2;Iris-setosa
4.6;3.1;1.5;0.2;Iris-setosa

### Tasks

**Task 1**

Create a data series where the values are integers from 1 to 100 and the indices are in the range from ean_001 to ean_100.

**Task 2**

Create a two-dimensional NumPy array of size 10x10, where the values are stored according to the following pattern:
```python
[
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024],
    [3, 9, 27 ... ],
    ...
    [10, 100, 1000, ... ]
]
```
The first column contains a number, which is then squared in the subsequent columns. Define this array as you see fit, but you are not allowed to enter this data “manually.”

Create a Pandas DataFrame from this data. Name the columns according to the pattern [‘base’, ‘pow_2’, ‘pow_3’, ..., ‘pow_10’]

**Task 3**

Check whether the NumPy array from the previous task and the pandas frame share the same data. If not, create another frame that shares this data with the array (you can use the method from previous labs to check this).

**Task 4**

Check the data type assigned to the frame from the previous task. Can it be downcast to a type that preserves the original data but reduces the amount of memory required to store it? Justify your answer with an appropriate code example.

**Task 5**

Read data from the `iris.data` file using the `read_csv` function into the `iris` variable, as shown in the example.

**Task 6**

Replace the column names in the `iris` frame so that spaces are replaced with the `_` character. Display the first 10 rows of this frame.

**Task 7**

Use the `memory_usage()` method (with and without the `deep=True` parameter) to check how much memory the frame occupies. Choose one of the float data types with lower precision and store the frame in a new variable `iris_smaller`, whose numeric columns will be cast to this new float type. Check again how much memory has been allocated for the frame.

**Task 8**

Save the frame to the clipboard (using the `to_clipboard()` function), then paste the clipboard contents into a text editor and any spreadsheet. Check the format of this data. 

Now copy a portion of this pasted data to the clipboard and save it to a new frame using the `from_clipboard()` method.
Display the first 5 rows of this clip.

The solution to this task is simply to call the above function; the rest is for the student’s information and knowledge.

**Task 9**

Install the frameworks for the `parquet`, `json`, and `pickle` formats (you may need to install additional packages) using the relevant functions described in the documentation (link provided in the materials).