# Data Analysis Techniques. Lab 5. Working with `pandas`, part 2.

# 1. Data selection

While statistics for an entire series or dataframe are useful, we are often interested in various subsets of data and their properties, which requires understanding (including by analogy with subsets we have already examined) the mechanisms for retrieving and filtering data in pandas. First, however, we will load the necessary data.

In the examples below, you should update the data path to match your local file storage structure.

In [12]:
import pandas as pd
import os

In [ ]:
# if the data folder is inside the same folder as your notebook
DATAPATH = './data'

In [ ]:
# link to the original dataset: https://www.kaggle.com/datasets/udaymalviya/bank-loan-data
df = pd.read_csv(os.path.join(DATAPATH, 'loan_data.csv'))

In [15]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

## 1.1 Selecting columns from pandas dataframe

In [ ]:
# single column selection - we provide a name for a column as we search for a value in dictionary
# by providing a key name
df['person_gender']

0        female
1        female
2        female
3        female
4          male
          ...
44995      male
44996    female
44997      male
44998      male
44999      male
Name: person_gender, Length: 45000, dtype: object

In [ ]:
# selecting many columns is also possible by providing a list of column names
df[['person_gender','person_education']]

      person_gender person_education
0            female           Master
1            female      High School
2            female      High School
3            female         Bachelor
4              male           Master
...             ...              ...
44995          male        Associate
44996        female        Associate
44997          male        Associate
44998          male         Bachelor
44999          male      High School

[45000 rows x 2 columns]

In [ ]:
# We can also access data in a column using the dot operator
# depending on whether the column names contain whitespace or not
df.person_gender

0        female
1        female
2        female
3        female
4          male
          ...
44995      male
44996    female
44997      male
44998      male
44999      male
Name: person_gender, Length: 45000, dtype: object

In [ ]:
# after selecting single (pandas Series) or multiple columns (pandas dataFrame) part we
# can use indexing or slicing to get ROWS that we are interested in
df['person_gender'][:5]

0    female
1    female
2    female
3    female
4      male
Name: person_gender, dtype: object

In [23]:
df[['person_gender','person_education']][:5]

  person_gender person_education
0        female           Master
1        female      High School
2        female      High School
3        female         Bachelor
4          male           Master

## 1.2 Selecting data using `.loc`, `.iloc`, and mapping with a boolean array

`.loc` uses label-based indexing, but you can also pass a boolean array. Labels refer to the values in the index column of a pandas series or pandas DataFrame, or the column names in a pandas DataFrame.

In [ ]:
# as pandas DataFrame is a two dimensional data type - we have two dimensions to provide indexes or slices for
# data selection
df.loc[:, 'person_gender']

0        female
1        female
2        female
3        female
4          male
          ...
44995      male
44996    female
44997      male
44998      male
44999      male
Name: person_gender, Length: 45000, dtype: object

In [ ]:
# We can also specify a value for only one dimension
# Here, we're looking for rows (default axis) where the “index” column has a value of 1, 2, or 3
df.loc[[1,2,3]]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1

In [31]:
df.loc[:5, ['person_gender', 'person_income']]

  person_gender  person_income
0        female        71948.0
1        female        12282.0
2        female        12438.0
3        female        79753.0
4          male        66135.0
5        female        12951.0

In [ ]:
# Note that the value for the first dimension (loc) is the actual value in the index column,
# not the index number of the elements in that index.
# Below is an example where the index has been changed to values starting from 1.
df.index = range(1, df.shape[0] + 1)

In [33]:
df[:5]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
5,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [ ]:
# now we are checking how loc works with the same parameters as iloc
df.loc[:5, ['person_gender', 'person_income']]

  person_gender  person_income
1        female        71948.0
2        female        12282.0
3        female        12438.0
4        female        79753.0
5          male        66135.0

**WARNING!**

Indexing using labels is performed with the stop value included, which is different from how classic slices work in Python!

Indexing with `.iloc` is similar to `.loc`, but here the letter `i` represents an index, so instead of column and row labels, we specify indices.

In [ ]:
# row indexes: 0-4, column indexes: 2 and 3
df.iloc[:5, 2:4]

  person_education  person_income
1           Master        71948.0
2      High School        12282.0
3      High School        12438.0
4         Bachelor        79753.0
5           Master        66135.0

In [ ]:
# Just like with the NumPy library, we can also manipulate the data in these areas, such as swapping the order of the columns
# although this isn’t usually necessary, since we can retrieve data from the frame in any column order
# Here’s the column order: third, second, and fourth columns (remember that indexing starts at 0?)
df.iloc[:, [2,1, 3]]

      person_education person_gender  person_income
1               Master        female        71948.0
2          High School        female        12282.0
3          High School        female        12438.0
4             Bachelor        female        79753.0
5               Master          male        66135.0
...                ...           ...            ...
44996        Associate          male        47971.0
44997        Associate        female        65800.0
44998        Associate          male        56942.0
44999         Bachelor          male        33164.0
45000      High School          male        51609.0

[45000 rows x 3 columns]

In [ ]:
# However, if we wanted to reorder them in the original grid, we could, for example, use the vector
# of the current column names from the .columns property
df.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

In [ ]:
# Let's say we want to swap columns 2 and 3
# For simplicity, we'll store the values of these labels in a Python list
old_columns = list(df.columns)
new_column_order = old_columns[:1] + old_columns[2:0:-1] + old_columns[3:]
new_column_order

['person_age',
 'person_education',
 'person_gender',
 'person_income',
 'person_emp_exp',
 'person_home_ownership',
 'loan_amnt',
 'loan_intent',
 'loan_int_rate',
 'loan_percent_income',
 'cb_person_cred_hist_length',
 'credit_score',
 'previous_loan_defaults_on_file',
 'loan_status']

In [ ]:
# Overwrite the variable with the original data frame, a new data frame with a different column order
df = df.loc[:, new_column_order]

In [56]:
df.head()

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
5,24.0,Master,male,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

**Selecting Data Using Boolean Value Tables**

This operation is typically used in data filtering, where a condition is applied to select data from a frame or series. Here, we can use the operators `|` (logical OR), `&` (logical AND), and `~` for negation.

In [ ]:
# returned type - a numpy array of boolean types (a mapping)
print(df['person_gender'] == 'female')

# now we apply the mapping to the data
df[df['person_gender'] == 'female']

1         True
2         True
3         True
4         True
5        False
         ...
44996    False
44997     True
44998    False
44999    False
45000    False
Name: person_gender, Length: 45000, dtype: bool

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
6,21.0,High School,female,12951.0,0,OWN,2500.0,VENTURE,7.14,0.19,2.0,532,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44989,28.0,Associate,female,49170.0,4,RENT,10401.0,HOMEIMPROVEMENT,11.97,0.21,6.0,677,No,1
44993,23.0,Bachelor,female,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,27.0,High School,female,35512.0,4,RENT,5000.0,PERSONAL,15.83,0.14,5.0,505,No,1
44995,24.0,Associate,female,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44997,37.0,Associate,female,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1

In [ ]:
# mapping with two conditions (& - this is a logical AND operator)
(df['loan_amnt'] > 10000) & (df['person_income'] < 50000)

1        False
2        False
3        False
4        False
5        False
         ...
44996     True
44997    False
44998    False
44999     True
45000    False
Length: 45000, dtype: bool

In [ ]:
# and now the data by applying the mapping
df[(df['loan_amnt'] > 10000) & (df['person_income'] < 50000)]

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
461,24.0,Associate,male,22684.0,0,OWN,13000.0,PERSONAL,7.88,0.57,3.0,640,No,1
494,23.0,Bachelor,male,43042.0,1,RENT,22250.0,DEBTCONSOLIDATION,12.69,0.52,3.0,678,No,1
536,22.0,High School,male,38473.0,0,RENT,21250.0,DEBTCONSOLIDATION,12.42,0.55,3.0,599,No,1
544,21.0,High School,male,42536.0,0,RENT,21000.0,VENTURE,12.53,0.49,4.0,687,No,1
547,26.0,Bachelor,female,48929.0,6,RENT,21000.0,MEDICAL,6.54,0.43,4.0,601,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44989,28.0,Associate,female,49170.0,4,RENT,10401.0,HOMEIMPROVEMENT,11.97,0.21,6.0,677,No,1
44992,24.0,High School,male,37786.0,0,MORTGAGE,13500.0,EDUCATION,13.43,0.36,4.0,612,No,1
44995,24.0,Associate,female,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44996,27.0,Associate,male,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44999,29.0,Bachelor,male,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1

In [ ]:
# and now we're completing this data by using the same condition and its negation
# an additional parenthesis has been added
df[~((df['loan_amnt'] > 10000) & (df['person_income'] < 50000))]

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
5,24.0,Master,male,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44993,23.0,Bachelor,female,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,27.0,High School,female,35512.0,4,RENT,5000.0,PERSONAL,15.83,0.14,5.0,505,No,1
44997,37.0,Associate,female,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44998,33.0,Associate,male,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
45000,24.0,High School,male,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [ ]:
# If we want to filter a column based on multiple values, it will be more useful and concise to
# use the isin() method
df['person_education'].isin(['Associate', 'High School'])

1        False
2         True
3         True
4        False
5        False
         ...
44996     True
44997     True
44998     True
44999    False
45000     True
Name: person_education, Length: 45000, dtype: bool

In [ ]:
# Filtering is also possible using a callable object,
# such as a built-in function or an anonymous function (lambda)
# Here are some examples

# Here, we first access the value `str` from this series, then apply the `startswith(‘D’)` method to each
# value in the series, which returns a Boolean array
map_1 = df['loan_intent'].str.startswith('D')

# Here's the same effect, but using `apply` (which maps something to each element of an iterable object) — here we map a function
# to each value in a given data series, and additionally pass the argument ‘D’ to the mapped function
map_2 = df['loan_intent'].apply(str.startswith, args='D')

# and yet another example - this time using anonymous function (lambda)
map_3 = df['loan_intent'].map(lambda x: x.startswith('D'))

map_1, map_2, map_3

In [ ]:
# Let's consider a scenario where we're interested in records where, after subtracting the loan amount
# from income, the remaining amount is greater than 50,000

# We can calculate this fairly easily
print(df['person_income'] - df['loan_amnt'])

# now we can use it as a condition (mapping)
netto_income_mapping = (df['person_income'] - df['loan_amnt']) > 50000
print(netto_income_mapping)

# and apply to the real data
df[netto_income_mapping]

# Can this also be done using a lambda function?

# A lambda function receives a parameter for each value returned by the iterator for the iterable
# on which it is called. In the previous case, it was a single data series, so the anonymous function received
# a single value from the series. Now let’s try another example where the function receives multiple values.

# Here, the lambda function’s argument is the entire record from the data frame; we can index it in any way
# that was presented earlier
df.apply(lambda x: (x['person_income'] - x['loan_amnt']) > 50000, axis=1)

1        36948.0
2        11282.0
3         6938.0
4        44753.0
5        31135.0
          ...
44996    32971.0
44997    56800.0
44998    54171.0
44999    21164.0
45000    44944.0
Length: 45000, dtype: float64
1        False
2        False
3        False
4        False
5        False
         ...
44996    False
44997     True
44998     True
44999    False
45000    False
Length: 45000, dtype: bool
1        False
2        False
3        False
4        False
5        False
         ...
44996    False
44997     True
44998     True
44999    False
45000    False
Length: 45000, dtype: bool

1        False
2        False
3        False
4        False
5        False
         ...
44996    False
44997     True
44998     True
44999    False
45000    False
Length: 45000, dtype: bool

## 1.3 Using `DataFrame.query`

In addition to the examples shown above, there is also the `query` method, which can be easier to write when filtering large sets of elements.

Examples in the documentation: https://pandas.pydata.org/docs/user_guide/indexing.html#the-query-method

Here are a few examples.

In [140]:
df.query('person_income > 100000')

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
9,24.0,Associate,female,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544,No,1
11,22.0,High School,female,102985.0,0,RENT,35000.0,VENTURE,10.37,0.34,4.0,621,No,1
13,23.0,Bachelor,male,114860.0,3,RENT,35000.0,VENTURE,7.90,0.30,2.0,573,No,1
14,26.0,Master,male,130713.0,0,RENT,35000.0,EDUCATION,18.39,0.27,4.0,708,No,1
15,23.0,Associate,female,138998.0,0,RENT,35000.0,EDUCATION,7.90,0.25,4.0,583,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44948,42.0,Doctorate,male,705960.0,21,MORTGAGE,20686.0,PERSONAL,10.74,0.03,16.0,689,No,1
44966,31.0,Associate,male,100407.0,9,RENT,17783.0,VENTURE,19.80,0.18,8.0,655,No,1
44973,43.0,Associate,male,184295.0,20,MORTGAGE,25000.0,EDUCATION,20.00,0.14,15.0,720,No,1
44983,26.0,Bachelor,male,130495.0,0,RENT,7622.0,PERSONAL,15.58,0.06,5.0,609,No,1
44991,31.0,Master,male,136832.0,9,RENT,12319.0,PERSONAL,16.92,0.09,7.0,722,No,1

In [ ]:
# Here, too, we can use the operators &, |, and ~
# As a reminder
# & - logical AND
# | - logical OR
# ~ - negation
display(df.query('person_education == "Doctorate" & person_age > 40'))
# code below 'person_education == ["Doctorate", "Master"] works like isin(["Doctorate", "Master"])
df.query('person_education == ["Doctorate", "Master"] & person_age > 40')

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
29160,41.0,Doctorate,female,301153.0,21,MORTGAGE,5000.0,EDUCATION,9.99,0.02,12.0,721,No,0
29207,42.0,Doctorate,male,18097.0,19,OWN,3500.0,MEDICAL,11.01,0.19,11.0,569,No,1
29272,41.0,Doctorate,male,72894.0,17,RENT,23800.0,HOMEIMPROVEMENT,6.91,0.33,15.0,755,No,1
29282,42.0,Doctorate,male,99557.0,18,RENT,22000.0,DEBTCONSOLIDATION,10.99,0.22,12.0,608,Yes,0
29302,45.0,Doctorate,male,45165.0,25,RENT,20000.0,HOMEIMPROVEMENT,11.71,0.44,15.0,579,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43925,41.0,Doctorate,male,119343.0,19,MORTGAGE,7663.0,MEDICAL,15.13,0.06,13.0,709,No,1
44098,43.0,Doctorate,male,38812.0,16,RENT,8746.0,MEDICAL,15.62,0.23,9.0,722,No,1
44628,47.0,Doctorate,male,70131.0,22,RENT,1500.0,MEDICAL,16.17,0.02,22.0,735,No,1
44699,43.0,Doctorate,female,72213.0,21,MORTGAGE,15000.0,PERSONAL,11.01,0.21,14.0,726,No,1
44948,42.0,Doctorate,male,705960.0,21,MORTGAGE,20686.0,PERSONAL,10.74,0.03,16.0,689,No,1

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
29125,45.0,Master,male,96924.0,25,RENT,35000.0,MEDICAL,11.01,0.36,13.0,566,No,1
29132,43.0,Master,female,600812.0,22,MORTGAGE,25000.0,VENTURE,12.61,0.04,14.0,685,No,0
29138,43.0,Master,female,480854.0,20,MORTGAGE,28000.0,VENTURE,9.91,0.06,11.0,619,No,0
29154,41.0,Master,female,322597.0,18,MORTGAGE,24000.0,PERSONAL,10.37,0.07,11.0,683,Yes,0
29160,41.0,Doctorate,female,301153.0,21,MORTGAGE,5000.0,EDUCATION,9.99,0.02,12.0,721,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44543,48.0,Master,female,65958.0,24,RENT,1169.0,DEBTCONSOLIDATION,14.14,0.02,21.0,704,No,1
44628,47.0,Doctorate,male,70131.0,22,RENT,1500.0,MEDICAL,16.17,0.02,22.0,735,No,1
44659,44.0,Master,female,21702.0,19,RENT,1500.0,PERSONAL,11.21,0.07,12.0,767,No,1
44699,43.0,Doctorate,female,72213.0,21,MORTGAGE,15000.0,PERSONAL,11.01,0.21,14.0,726,No,1
44948,42.0,Doctorate,male,705960.0,21,MORTGAGE,20686.0,PERSONAL,10.74,0.03,16.0,689,No,1

## Tasks

1. Rename the column `loan_amnt` to `loan_amount`.

2. From the data frame used in the examples (loan), display:
   * a) only the columns `person_gender`, `person_age`, and `person_income`,
   * b) rows from 1000 through 2000 inclusive (this refers to consecutive rows in the dataset, not the index value),
   * c) even-numbered rows,
   * d) rows with an even value in the index column,
   * e) the first and last columns with one function call.

3. From the same data frame, display data using filters (conditions):
   * a) only women with a `Master` or `Bachelor` degree and loans between 50,000 and 70,000,
   * b) all men with an education level other than `Master` and who own a home (`person_home_ownership` column = `OWN`),
   * c) all individuals with a `loan_percent_income` value between 0.4 and 0.6,
   * d) all loan amounts that are multiples of 10,000.